[workspace]
resolver = "2"
members = [
    "crates/aruco",
    "crates/controller",
    "crates/motor",
]

[workspace.package]
version = "0.0.1"
edition = "2021"

[workspace.dependencies]
# aruco
opencv = "0.94.4"
# moter
rppal = { version = "0.22.1", features = ["hal"] }
